-- GIN index on Entry.metadata (not generated by Prisma — added manually)
CREATE INDEX "entry_metadata_idx" ON "entry" USING GIN ("metadata" jsonb_ops);

-- search_vector trigger on Translation
-- Fires on INSERT or UPDATE.
-- Extracts all "text" nodes from blocks via jsonb_path_query,
-- combines with term and metadata->>'definition_short',
-- and calls to_tsvector with the locale-appropriate dictionary.
-- Falls back to 'simple' for locales without a built-in Postgres dictionary.

CREATE OR REPLACE FUNCTION translation_search_vector_update()
RETURNS trigger AS $$
DECLARE
  dict       regconfig;
  block_text text;
BEGIN
  -- Only 'english', 'german', 'french', 'norwegian' are available in the default
  -- Postgres install. Polish and other locales fall back to 'simple' (no stemming).
  dict := CASE NEW.locale
    WHEN 'de'    THEN 'german'::regconfig
    WHEN 'no'    THEN 'norwegian'::regconfig
    WHEN 'fr'    THEN 'french'::regconfig
    WHEN 'en'    THEN 'english'::regconfig
    WHEN 'en-US' THEN 'english'::regconfig
    WHEN 'en-GB' THEN 'english'::regconfig
    ELSE              'simple'::regconfig
  END;

  SELECT string_agg(val::text, ' ')
    INTO block_text
    FROM jsonb_path_query(NEW.blocks, 'strict $.**.text ? (@ != null)') val;

  NEW.search_vector := to_tsvector(
    dict,
    coalesce(NEW.term, '') || ' ' ||
    coalesce(NEW.metadata->>'definition_short', '') || ' ' ||
    coalesce(block_text, '')
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER translation_search_vector_trigger
  BEFORE INSERT OR UPDATE ON "translation"
  FOR EACH ROW EXECUTE FUNCTION translation_search_vector_update();
